### ISSUE TITLE
response status is always 500. server error

### ISSUE THREAD

**Issue by gametack** [sopherapps/mtn-pay-js#13]
This is a great package and nicely written. Though I'm not sure how you're testing this or getting it to work. Momo server seems to enforce title headers yet axiom and most http clients force lowercase header. Therefore each call I've made so far with the exception of getting the access token returns 500 Server Error.

I've verified this behavior with postman. If the headers are anything by titlecase, it returns error 500.
I tested with the collection account balance endpoint.

BTW I didn't make the call for the access token directly as your package does not expose it, I simply printed the response before the call was made.

Can you please let me know if there's a way around it, of if I'm just missing something.
Thanks.

**Comment by Tinitto** [comment]
@gametack I'm so sorry to hear all this almost a year later. MOMO pay API was so unstable that I gave up on it.

**Comment by Tinitto** [comment]
I am closing this conversation and archiving this repo.
